name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            artifact_name: app-windows.zip
          - os: ubuntu-latest
            artifact_name: app-linux.zip
          - os: macos-latest
            artifact_name: app-macos.zip

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build
        run: pyinstaller build_config.spec

      - name: Create ZIP archive
        run: |
          cd dist
          7z a -tzip ../${{ matrix.artifact_name }} *

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ matrix.artifact_name }}
          draft: false
          prerelease: false
          generate_release_notes: true